# Generated by Django 4.2.3 on 2025-09-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='dummy_field',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
