# Generated by Django 4.2.3 on 2025-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduTrack', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='dummy_field',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
