# Generated by Django 4.2.3 on 2025-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduTrack', '0004_adminuser_dummy_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='add',
            field=models.IntegerField(default=0),
        ),
    ]
